import { SpotifyProvider } from '@/app/context/SpotifyContext';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body>
      <SpotifyProvider>{children}</SpotifyProvider>
      </body>
      </html>
  )
}